# Generated by Django 5.0.6 on 2024-09-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('companyId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=100)),
                ('adminEmail', models.EmailField(max_length=254)),
                ('adminPhoneNum', models.CharField(max_length=15)),
                ('companyName', models.CharField(max_length=100)),
                ('companyRegisteredId', models.CharField(max_length=100)),
                ('pan', models.CharField(max_length=20)),
                ('tan', models.CharField(max_length=20)),
                ('gst', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('coi', models.ImageField(blank=True, null=True, upload_to='coi/')),
                ('address', models.TextField()),
                ('leavePolicy', models.FileField(blank=True, null=True, upload_to='leave_policies/')),
                ('pfPolicy', models.FileField(blank=True, null=True, upload_to='pf_policies/')),
                ('labourLawLicence', models.FileField(blank=True, null=True, upload_to='labour_law_policies/')),
            ],
        ),
    ]
